"""Add image_key to post model

Revision ID: bac1ff2756d2
Revises: add_post_tsvector
Create Date: 2025-07-26 00:25:20.199271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac1ff2756d2'
down_revision: Union[str, Sequence[str], None] = 'add_post_tsvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_key', sa.String(length=256), nullable=True))
    op.drop_index(op.f('ix_post_tsv'), table_name='post', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_tsv'), 'post', ['tsv'], unique=False, postgresql_using='gin')
    op.drop_column('post', 'image_key')
    # ### end Alembic commands ###
